name: Deploy to Prod
run-name: Deploy Prod — ${{ github.actor }}

on:
  push:
    branches:
      - prod

env:
  SSH_HOST_PROD: ${{ secrets.SSH_HOST }}
  SSH_PORT_PROD: ${{ secrets.SSH_PORT }}
  SSH_USER_PROD: ${{ secrets.SSH_USER_PROD }}
  REMOTE_PLUGIN_DIR_PROD: ${{ secrets.REMOTE_PLUGIN_DIR_PROD }}

  SSH_HOST_EVENT: ${{ secrets.SSH_HOST }}
  SSH_PORT_EVENT: ${{ secrets.SSH_PORT }}
  SSH_USER_EVENT: ${{ secrets.SSH_USER_PROD }}
  REMOTE_PLUGIN_DIR_EVENT: ${{ secrets.REMOTE_PLUGIN_DIR_EVENT }}

jobs:
  deploy_prod:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh

          ssh-keyscan -p "${{ secrets.SSH_PORT_PROD }}" "${{ secrets.SSH_HOST_PROD }}" >> ~/.ssh/known_hosts
          ssh-keyscan -p "${{ secrets.SSH_PORT_EVENT }}" "${{ secrets.SSH_HOST_EVENT }}" >> ~/.ssh/known_hosts

      - name: Ensure repository is up to date
        run: |
          git config pull.rebase true
          git pull origin prod

      - name: Validate
        run: |
          echo "Init terminé sur la branche : ${{ github.ref_name }}"
          echo "Commit : ${{ github.sha }}"
          echo "Auteur : ${{ github.actor }}"
          echo "DEPLOIEMENT PRODUCTION + EVENT"

      # =========================
      # PROD DEPLOY
      # =========================

      - name: Ensure PROD directory exists
        run: |
          ssh -p "${{ secrets.SSH_PORT_PROD }}" \
            "${{ secrets.SSH_USER_PROD }}@${{ secrets.SSH_HOST_PROD }}" \
            "mkdir -p ${{ secrets.REMOTE_PLUGIN_DIR_PROD }}"

      - name: Sync to PROD
        run: |
          rsync -avz --delete \
            -e "ssh -p ${{ secrets.SSH_PORT_PROD }}" \
            notif/ \
            "${{ secrets.SSH_USER_PROD }}@${{ secrets.SSH_HOST_PROD }}:${{ secrets.REMOTE_PLUGIN_DIR_PROD }}"

      # =========================
      # EVENT DEPLOY
      # =========================

      - name: Ensure EVENT directory exists
        run: |
          ssh -p "${{ secrets.SSH_PORT_EVENT }}" \
            "${{ secrets.SSH_USER_EVENT }}@${{ secrets.SSH_HOST_EVENT }}" \
            "mkdir -p ${{ secrets.REMOTE_PLUGIN_DIR_EVENT }}"

      - name: Sync to EVENT
        run: |
          rsync -avz --delete \
            -e "ssh -p ${{ secrets.SSH_PORT_EVENT }}" \
            notif/ \
            "${{ secrets.SSH_USER_EVENT }}@${{ secrets.SSH_HOST_EVENT }}:${{ secrets.REMOTE_PLUGIN_DIR_EVENT }}"

      - name: Done
        run: |
          echo "Deploy Prod + Event terminé avec succès"